[package]
name = "dtex"
version = "0.0.0"
edition = "2021"

[dependencies]
# Efficient allocator
mimalloc = { version = "0.1", default-features = false }
# Terminal UI
tui = { git = "https://github.com/Virgiel/tui" }
# Line editor tool
reedline = "0.19.0"
# Temporary file
tempfile = "3.5.0"
# DataFrame engine
polars = { version = "0.29.0", features = [
    "performant",
    "json",
    "avro",
    "ipc",
    "parquet",
    "lazy",
    "sql",
] }
# Binary string helper
bstr = "1.4.0"
# Fast lexical conversion
lexical-core = "0.8.5"
# Time library
chrono = "0.4.24"
# CLI args parser
clap = { version = "4.2.2", features = ["derive"] }
# Regular expression lib
regex = "1.8.1"

[workspace]
members = ["py-dtex"]
